Feature/15/button component
nology-tech/Tahiti-Client-Project pull request #14
Opened 2023-05-09 15:04 UTC by henryadamsgit

Completed buttons

2023-05-09 15:33 UTC, olirob93 requested changes
Looks good, I think I might have confused you when I said have you put the button where it needs to.

It should only be used where we already have components using a button. We don't want to add the button in random places as it will be used when we create other components.

2023-05-09 15:33 UTC, olirob93 commented on src/pages/WelcomePage/WelcomePage.scss
> +@use "../../components/Button/Button.scss" as *;
Does this need to be here?

2023-05-09 15:33 UTC, olirob93 commented on src/pages/WelcomePage/WelcomePage.jsx
> +const WelcomePage = ({ setUser, buttonStyle }) => {
Button style doesn't need to be in the props does it?

2023-05-09 15:33 UTC, olirob93 commented on src/pages/WelcomePage/WelcomePage.jsx
> +            className={buttonStyle}
classname can be removed

2023-05-09 15:33 UTC, olirob93 commented on src/components/HomepageCard/HomepageCard.jsx
button style can be removed from all places in this component

2023-05-09 15:33 UTC, olirob93 commented on src/components/HomepageCard/HomepageCard.scss
do you need the scss imported here

2023-05-09 15:33 UTC, olirob93 commented on src/pages/Booking/Booking.jsx
button style can be removed from everywhere in this file

2023-05-09 15:33 UTC, olirob93 commented on src/pages/Booking/Booking.scss
remove this scss we shouldn't have put the buttons in unless it was replacing it from a component

2023-05-09 15:33 UTC, olirob93 commented on src/pages/Clients/Clients.jsx
remove the button from here

2023-05-09 15:33 UTC, olirob93 commented on src/pages/Resources/Resources.jsx
remove the button from here

2023-05-09 15:33 UTC, olirob93 commented on src/pages/Settings/Settings.jsx
remove the button from here

2023-05-09 15:33 UTC, olirob93 commented on src/pages/Staff/Staff.jsx
remove the button from here

2023-05-09 15:52 UTC, henryadamsgit commented on src/pages/Booking/Booking.scss
Remove all scss or just the button import?

2023-05-10 10:13 UTC, olirob93 requested changes
formatting issues

2023-05-10 10:13 UTC, olirob93 commented on src/components/HomepageCard/HomepageCard.scss
> +
whtie space

2023-05-10 10:13 UTC, olirob93 commented on src/pages/Booking/Booking.jsx
nothing should be different in this file

2023-05-10 10:13 UTC, olirob93 commented on src/pages/Booking/Booking.scss
> +
still has a line

2023-05-10 10:13 UTC, olirob93 commented on src/pages/Resources/Resources.jsx
> +      <SideNav />
no space here for sideNav

2023-05-10 11:04 UTC, olirob93 approved these changes
all good

2023-05-10 11:05 UTC, merged